### ISSUE TITLE
Make StrongPath Hasheable

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/strong-path#43]
https://hackage.haskell.org/package/hashable-1.4.0.1/docs/Data-Hashable.html#t:Hashable

Ideally we could just forward to the Hasheable instance of `Path`, but there is some extra info we keep next to the `Path`, that might not be viable, and we will have to do it on our own.

This is important to enable usage of StrongPath in certain situations, for example as a key in a HashMap.

**Comment by Martinsos** [comment]
Actually I am being silly, we should be able to just call `toFilePath` on it and then hash that! That should be super easy.

**Comment by craigmc08** [comment]
This looks fixed: https://github.com/wasp-lang/strong-path/blob/main/src/StrongPath/Instances.hs#L19

**Comment by Martinsos** [comment]
Oh right, thanks!
